# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_change_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 360)
        self.ttab_tabl_rbtn = QtWidgets.QRadioButton(Dialog)
        self.ttab_tabl_rbtn.setGeometry(QtCore.QRect(165, 40, 105, 20))
        self.ttab_tabl_rbtn.setObjectName("ttab_tabl_rbtn")
        self.tabl_rbtns = QtWidgets.QButtonGroup(Dialog)
        self.tabl_rbtns.setObjectName("tabl_rbtns")
        self.tabl_rbtns.addButton(self.ttab_tabl_rbtn)
        self.dead_tabl_rbtn = QtWidgets.QRadioButton(Dialog)
        self.dead_tabl_rbtn.setGeometry(QtCore.QRect(165, 10, 105, 20))
        self.dead_tabl_rbtn.setObjectName("dead_tabl_rbtn")
        self.tabl_rbtns.addButton(self.dead_tabl_rbtn)
        self.add_oper_rbtn = QtWidgets.QRadioButton(Dialog)
        self.add_oper_rbtn.setGeometry(QtCore.QRect(30, 10, 105, 20))
        self.add_oper_rbtn.setObjectName("add_oper_rbtn")
        self.oper_rbtns = QtWidgets.QButtonGroup(Dialog)
        self.oper_rbtns.setObjectName("oper_rbtns")
        self.oper_rbtns.addButton(self.add_oper_rbtn)
        self.chg_oper_rbtn = QtWidgets.QRadioButton(Dialog)
        self.chg_oper_rbtn.setGeometry(QtCore.QRect(30, 40, 105, 20))
        self.chg_oper_rbtn.setObjectName("chg_oper_rbtn")
        self.oper_rbtns.addButton(self.chg_oper_rbtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ttab_tabl_rbtn.setText(_translate("Dialog", "Time Table"))
        self.dead_tabl_rbtn.setText(_translate("Dialog", "Deadline"))
        self.add_oper_rbtn.setText(_translate("Dialog", "Add"))
        self.chg_oper_rbtn.setText(_translate("Dialog", "Change"))
