# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_change_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 360)
        self.ttab_tabl_rbtn = QtWidgets.QRadioButton(Dialog)
        self.ttab_tabl_rbtn.setGeometry(QtCore.QRect(165, 40, 105, 20))
        self.ttab_tabl_rbtn.setObjectName("ttab_tabl_rbtn")
        self.tabl_rbtns = QtWidgets.QButtonGroup(Dialog)
        self.tabl_rbtns.setObjectName("tabl_rbtns")
        self.tabl_rbtns.addButton(self.ttab_tabl_rbtn)
        self.dead_tabl_rbtn = QtWidgets.QRadioButton(Dialog)
        self.dead_tabl_rbtn.setGeometry(QtCore.QRect(165, 10, 105, 20))
        self.dead_tabl_rbtn.setObjectName("dead_tabl_rbtn")
        self.tabl_rbtns.addButton(self.dead_tabl_rbtn)
        self.add_oper_rbtn = QtWidgets.QRadioButton(Dialog)
        self.add_oper_rbtn.setGeometry(QtCore.QRect(30, 10, 105, 20))
        self.add_oper_rbtn.setObjectName("add_oper_rbtn")
        self.oper_rbtns = QtWidgets.QButtonGroup(Dialog)
        self.oper_rbtns.setObjectName("oper_rbtns")
        self.oper_rbtns.addButton(self.add_oper_rbtn)
        self.chg_oper_rbtn = QtWidgets.QRadioButton(Dialog)
        self.chg_oper_rbtn.setGeometry(QtCore.QRect(30, 40, 105, 20))
        self.chg_oper_rbtn.setChecked(True)
        self.chg_oper_rbtn.setObjectName("chg_oper_rbtn")
        self.oper_rbtns.addButton(self.chg_oper_rbtn)
        self.select_cbx = QtWidgets.QComboBox(Dialog)
        self.select_cbx.setGeometry(QtCore.QRect(10, 70, 280, 20))
        self.select_cbx.setEditable(True)
        self.select_cbx.setObjectName("select_cbx")
        self.title_edt = QtWidgets.QLineEdit(Dialog)
        self.title_edt.setGeometry(QtCore.QRect(10, 100, 280, 20))
        self.title_edt.setObjectName("title_edt")
        self.start_date_edt = QtWidgets.QDateEdit(Dialog)
        self.start_date_edt.setGeometry(QtCore.QRect(140, 130, 120, 20))
        self.start_date_edt.setObjectName("start_date_edt")
        self.start_time_edt = QtWidgets.QTimeEdit(Dialog)
        self.start_time_edt.setGeometry(QtCore.QRect(140, 160, 120, 20))
        self.start_time_edt.setObjectName("start_time_edt")
        self.start_txt = QtWidgets.QLabel(Dialog)
        self.start_txt.setGeometry(QtCore.QRect(20, 145, 50, 20))
        self.start_txt.setObjectName("start_txt")
        self.end_txt = QtWidgets.QLabel(Dialog)
        self.end_txt.setGeometry(QtCore.QRect(20, 205, 50, 20))
        self.end_txt.setObjectName("end_txt")
        self.end_time_edt = QtWidgets.QTimeEdit(Dialog)
        self.end_time_edt.setGeometry(QtCore.QRect(140, 220, 120, 20))
        self.end_time_edt.setObjectName("end_time_edt")
        self.end_date_edt = QtWidgets.QDateEdit(Dialog)
        self.end_date_edt.setGeometry(QtCore.QRect(140, 190, 120, 20))
        self.end_date_edt.setObjectName("end_date_edt")
        self.period_txt = QtWidgets.QLabel(Dialog)
        self.period_txt.setGeometry(QtCore.QRect(20, 250, 50, 20))
        self.period_txt.setObjectName("period_txt")
        self.period_days_edt = QtWidgets.QSpinBox(Dialog)
        self.period_days_edt.setGeometry(QtCore.QRect(140, 250, 120, 20))
        self.period_days_edt.setObjectName("period_days_edt")
        self.commit_btn = QtWidgets.QPushButton(Dialog)
        self.commit_btn.setGeometry(QtCore.QRect(10, 300, 280, 40))
        self.commit_btn.setObjectName("commit_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ttab_tabl_rbtn.setText(_translate("Dialog", "Time Table"))
        self.dead_tabl_rbtn.setText(_translate("Dialog", "Deadline"))
        self.add_oper_rbtn.setText(_translate("Dialog", "Add"))
        self.chg_oper_rbtn.setText(_translate("Dialog", "Change"))
        self.start_txt.setText(_translate("Dialog", "start"))
        self.end_txt.setText(_translate("Dialog", "end"))
        self.period_txt.setText(_translate("Dialog", "period"))
        self.commit_btn.setText(_translate("Dialog", "Add"))
