# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeTable(object):
    def setupUi(self, TimeTable):
        TimeTable.setObjectName("TimeTable")
        TimeTable.resize(550, 405)
        self.centralwidget = QtWidgets.QWidget(TimeTable)
        self.centralwidget.setObjectName("centralwidget")
        self.ttab_tabl = QtWidgets.QTableWidget(self.centralwidget)
        self.ttab_tabl.setGeometry(QtCore.QRect(280, 20, 260, 300))
        self.ttab_tabl.setObjectName("ttab_tabl")
        self.ttab_tabl.setColumnCount(0)
        self.ttab_tabl.setRowCount(0)
        self.dead_tabl = QtWidgets.QTableWidget(self.centralwidget)
        self.dead_tabl.setGeometry(QtCore.QRect(10, 20, 260, 300))
        self.dead_tabl.setObjectName("dead_tabl")
        self.dead_tabl.setColumnCount(0)
        self.dead_tabl.setRowCount(0)
        self.dead_tabl.verticalHeader().setMinimumSectionSize(23)
        self.ttab_txt = QtWidgets.QLabel(self.centralwidget)
        self.ttab_txt.setGeometry(QtCore.QRect(280, 0, 261, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ttab_txt.setFont(font)
        self.ttab_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.ttab_txt.setObjectName("ttab_txt")
        self.dead_txt = QtWidgets.QLabel(self.centralwidget)
        self.dead_txt.setGeometry(QtCore.QRect(10, 0, 261, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.dead_txt.setFont(font)
        self.dead_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.dead_txt.setObjectName("dead_txt")
        self.view_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_btn.setGeometry(QtCore.QRect(10, 354, 530, 25))
        self.view_btn.setObjectName("view_btn")
        self.view_btns = QtWidgets.QButtonGroup(TimeTable)
        self.view_btns.setObjectName("view_btns")
        self.view_btns.addButton(self.view_btn)
        self.date_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.date_back_btn.setGeometry(QtCore.QRect(10, 323, 70, 30))
        self.date_back_btn.setObjectName("date_back_btn")
        self.date_forw_btn = QtWidgets.QPushButton(self.centralwidget)
        self.date_forw_btn.setGeometry(QtCore.QRect(470, 323, 70, 30))
        self.date_forw_btn.setObjectName("date_forw_btn")
        self.date_txt = QtWidgets.QLabel(self.centralwidget)
        self.date_txt.setGeometry(QtCore.QRect(80, 323, 391, 30))
        self.date_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.date_txt.setObjectName("date_txt")
        TimeTable.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TimeTable)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        TimeTable.setMenuBar(self.menubar)

        self.retranslateUi(TimeTable)
        QtCore.QMetaObject.connectSlotsByName(TimeTable)

    def retranslateUi(self, TimeTable):
        _translate = QtCore.QCoreApplication.translate
        TimeTable.setWindowTitle(_translate("TimeTable", "MainWindow"))
        self.ttab_txt.setText(_translate("TimeTable", "Time Table"))
        self.dead_txt.setText(_translate("TimeTable", "Dead Lines"))
        self.view_btn.setText(_translate("TimeTable", "View"))
        self.date_back_btn.setText(_translate("TimeTable", "<"))
        self.date_forw_btn.setText(_translate("TimeTable", ">"))
        self.date_txt.setText(_translate("TimeTable", "TextLabel"))
