# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ttab_tabl = QtWidgets.QTableWidget(self.centralwidget)
        self.ttab_tabl.setGeometry(QtCore.QRect(220, 20, 200, 300))
        self.ttab_tabl.setObjectName("ttab_tabl")
        self.ttab_tabl.setColumnCount(0)
        self.ttab_tabl.setRowCount(0)
        self.dead_tabl = QtWidgets.QTableWidget(self.centralwidget)
        self.dead_tabl.setGeometry(QtCore.QRect(10, 20, 200, 300))
        self.dead_tabl.setObjectName("dead_tabl")
        self.dead_tabl.setColumnCount(0)
        self.dead_tabl.setRowCount(0)
        self.dead_tabl.verticalHeader().setMinimumSectionSize(23)
        self.ttab_txt = QtWidgets.QLabel(self.centralwidget)
        self.ttab_txt.setGeometry(QtCore.QRect(220, 0, 200, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ttab_txt.setFont(font)
        self.ttab_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.ttab_txt.setObjectName("ttab_txt")
        self.dead_txt = QtWidgets.QLabel(self.centralwidget)
        self.dead_txt.setGeometry(QtCore.QRect(10, 0, 200, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.dead_txt.setFont(font)
        self.dead_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.dead_txt.setObjectName("dead_txt")
        self.view_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_btn.setGeometry(QtCore.QRect(10, 354, 411, 25))
        self.view_btn.setObjectName("view_btn")
        self.view_btns = QtWidgets.QButtonGroup(MainWindow)
        self.view_btns.setObjectName("view_btns")
        self.view_btns.addButton(self.view_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(10, 379, 411, 25))
        self.refresh_btn.setObjectName("refresh_btn")
        self.date_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.date_back_btn.setGeometry(QtCore.QRect(10, 323, 70, 30))
        self.date_back_btn.setObjectName("date_back_btn")
        self.date_forw_btn = QtWidgets.QPushButton(self.centralwidget)
        self.date_forw_btn.setGeometry(QtCore.QRect(350, 323, 70, 30))
        self.date_forw_btn.setObjectName("date_forw_btn")
        self.date_txt = QtWidgets.QLabel(self.centralwidget)
        self.date_txt.setGeometry(QtCore.QRect(80, 323, 270, 30))
        self.date_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.date_txt.setObjectName("date_txt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ttab_txt.setText(_translate("MainWindow", "Time Table"))
        self.dead_txt.setText(_translate("MainWindow", "Dead Lines"))
        self.view_btn.setText(_translate("MainWindow", "View"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.date_back_btn.setText(_translate("MainWindow", "<"))
        self.date_forw_btn.setText(_translate("MainWindow", ">"))
        self.date_txt.setText(_translate("MainWindow", "TextLabel"))
