# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 415)
        self.viewer_tbl = QtWidgets.QTableWidget(Dialog)
        self.viewer_tbl.setGeometry(QtCore.QRect(0, 0, 550, 415))
        self.viewer_tbl.setObjectName("viewer_tbl")
        self.viewer_tbl.setColumnCount(0)
        self.viewer_tbl.setRowCount(0)
        self.change_btn = QtWidgets.QPushButton(Dialog)
        self.change_btn.setGeometry(QtCore.QRect(560, 375, 150, 30))
        self.change_btn.setObjectName("change_btn")
        self.month_txt = QtWidgets.QLabel(Dialog)
        self.month_txt.setGeometry(QtCore.QRect(590, 15, 85, 40))
        self.month_txt.setObjectName("month_txt")
        self.back_month_btn = QtWidgets.QPushButton(Dialog)
        self.back_month_btn.setGeometry(QtCore.QRect(550, 15, 40, 40))
        self.back_month_btn.setObjectName("back_month_btn")
        self.forward_month_btn = QtWidgets.QPushButton(Dialog)
        self.forward_month_btn.setGeometry(QtCore.QRect(675, 15, 40, 40))
        self.forward_month_btn.setObjectName("forward_month_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.change_btn.setText(_translate("Dialog", "Edit"))
        self.month_txt.setText(_translate("Dialog", "month"))
        self.back_month_btn.setText(_translate("Dialog", "PushButton"))
        self.forward_month_btn.setText(_translate("Dialog", "PushButton"))
